### ISSUE TITLE
app stops working when entering supply-only ports

### ISSUE THREAD

**Issue by jiayu2019** [JohanLi/uncharted-waters-2#7]
When I press 'e'  to enter Wanganui, the app stops working.

**Comment by JohanLi** [comment]
Hi @jiayu2019 and thank you for this report! Sailing all the way to Wanganui from Lisbon certainly isn't an easy feat :star:

Supply ports have finally been implemented now, and here's how Wanganui looks:

<img width="841" alt="supply-ports-fixed" src="https://user-images.githubusercontent.com/6412575/149361545-34dc61d7-28e4-4e94-b7c3-7dcb07889d7f.png">
