### ISSUE TITLE
cursor arrow direction

### ISSUE THREAD

**Issue by jiayu2019** [JohanLi/uncharted-waters-2#8]
Which ever direction I sail to, the cursor arrow is always pointing to east(right).

**Comment by JohanLi** [comment]
Thanks for the report!

The cursor arrow's direction changes through using JS to update `cursor: url()`, setting a data URI along with a position. This approach was/still might not be fool-proof across all browsers.

In the latest release, I've decided to abandon cursor arrows – movement and sailing is now done through WASD.

In the future, I think the "Set your destination" feature with a wheel cursor could be something I'll implement.

![image](https://user-images.githubusercontent.com/6412575/149364920-f8e15706-91d5-41b4-bc5c-aae9f2758c0c.png)
